//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public long comId { get; set; }
        public long imgId { get; set; }
        public long usrId { get; set; }
        public string message { get; set; }
        public System.DateTime PostDate { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
