//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public long comId { get; set; }
        public long imgId { get; set; }
        public long usrId { get; set; }
        public string message { get; set; }
        public System.DateTime postDate { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
